### ISSUE TITLE
Timeline highlighting on mouse-over of comments

### ISSUE THREAD

**Issue by jamesscottbrown** [visdesignlab/coronavirus-annotation-2#28]
When the user mouses-over an annotation in the left-hand pane, the background changes for all of the bars in the annotation timeline.

It would be more useful to highlight the specific bar corresponding to the annotation (as is currently done for comments).

**Comment by jrogerthat** [comment]
Thanks for catching that! That was a bug from when I switched over the annotation sheet. It's been fixed :)
