### ISSUE TITLE
Add more information to About page

### ISSUE THREAD

**Issue by jamesscottbrown** [visdesignlab/coronavirus-annotation-2#38]
Some of the background information from https://animationlab.utah.edu/cova (e.g., that it is an Animation Lab/Vis Design Lab collaboration funded by the NSF) should be accessible by clicking the `About` link.

This could be added to the `info-blurb` overlay, or the link that displays the overlay could be relabeled to `Help` and a separate `About` page could be created.

**Comment by jrogerthat** [comment]
I added a home icon with the link! Might change this but I wanted to have that option to go back to the project page asap
